### ISSUE TITLE
Rounded corners?

### ISSUE THREAD

**Issue by Nikzed** [rafid08/media_picker_widget#14]
Where there ever be rounded corners for bottom sheet? Really necessary for the modern design. Thank you!
<img width="349" alt="image" src="https://github.com/rafidgotit/media_picker_widget/assets/38156331/d2e3ae3a-f277-4b24-b65b-e531e2dc8b9d">

**Comment by rafidgotit** [comment]
Just create a bottomsheet with rounded corner and then place the widget in it? 
🤷‍♂️🤷‍♂️🤷‍♂️
