### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(PERMISSION_REQUESTING, Another permission request is still ongoing. Please request after the existing one is done., null, null)

### ISSUE THREAD

**Issue by bugrevealingbme** [rafid08/media_picker_widget#3]
There is a problem getting the photos on the first launch.

D/CompatibilityChangeReporter(  759): Compat change id reported: 78294732; UID 10152; state: DISABLED
E/flutter (  759): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(PERMISSION_REQUESTING, Another permission request is still ongoing. Please request after the existing one is done., null, null)
E/flutter (  759): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:607
E/flutter (  759): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:167

**Comment by rafidgotit** [comment]
This issue should be solved by now. 
I couldn't reproduce this issue in android.
Maybe you were using another permission handler package that was trying to ask permission at the same time this package was asking...
