### ISSUE TITLE
The argument type 'Uint8List?' can't be assigned to the parameter type 'Uint8List'

### ISSUE THREAD

**Issue by AMANUELAB** [rafid08/media_picker_widget#4]
The argument type 'Uint8List?' can't be assigned to the parameter type 'Uint8List'

**Comment by rafid08** [comment]
Is it in the latest version?

**Comment by rafidgotit** [comment]
You have to check if the variable you are getting is null or not.
Read the docs about null safety in flutter. 
https://dart.dev/null-safety
