### ISSUE TITLE
Header bar customization

### ISSUE THREAD

**Issue by reliance-engineer** [rafid08/media_picker_widget#6]
Hi, first I would like to say that I really found this plugin very good, I've been using it in several projects and It have saved me thousand hours!! So KUDOS to the devs!!

I have a request, I would like to have more customisation, specifically in the `Header` to be able to achieve some complex requirements as the one I show in the image.

![image](https://user-images.githubusercontent.com/114175138/221369365-3174458c-de1e-4208-876e-169c1749c1d7.png)

Right now the `Header` has an this alignment `mainAxisAlignment: MainAxisAlignment.spaceAround,`  that doesn't allow to move the album selector. 

Specifically the changes I'm requesting are:
1. Allow the developer to set the Header bar alignment
2. Allow the user to hide the button on `MediaCount.multiple`

Thanks in advance!!

**Comment by rafidgotit** [comment]
hey @reliance-engineer ,
Thank you so much for you appreciation.
I've just released `1.0.1` version of this package where you can add custom header using `HeaderBuilder`.
Check the doc for details.
https://pub.dev/packages/media_picker_widget#custom-header

Ask me anything if you need help.
Also sorry for being late...

**Comment by reliance-engineer** [comment]
Thank you so much!!
