### ISSUE TITLE
Ability to also style selected counter

### ISSUE THREAD

**Issue by davie1989** [rafid08/media_picker_widget#8]
Hi. I must say the plugin is a time saver. I was just considering the time I will need to spare to implement a media picker using the photo manager plugin. 

I will be glad if the author can add the ability to style selected file round badge.

I can style other things like completeButton and album file count button

Thanks.

**Comment by rafidgotit** [comment]
Hey @davie1989 
Thanks for your appreciation. 
`1.0.4` version has been uploaded.
You can use `counterBuilder` in `PickerDecoration` to customize the counter.
Visit api reference for more info.
