### ISSUE TITLE
Android SDK 33 not working, how fix out?

### ISSUE THREAD

**Issue by akashjpro** [rafid08/media_picker_widget#9]
When I run device android SDK 33 but media picker widget not working.
How fix out?
Thanks!

**Comment by rafidgotit** [comment]
@akashjpro 
Storage Permissions in Android SDK 33 has been updated. You have to add the following permissions in your `AndroidManifest.xml`

`READ_MEDIA_IMAGES`
`READ_MEDIA_VIDEO`

I should have updated the documentation. It will be in the next update InshaAllah.
Hope this helps...

Example Code:
```
<uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
<uses-permission android:name="android.permission.READ_MEDIA_VIDEO"/>
```

Reference: 
https://developer.android.com/about/versions/13/behavior-changes-13
